config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root to: 'splatoons#index'
get 'splatoons', to: 'splatoons#index'
get 'list2s/index' , to: 'list2s#index'
get 'rules', to: 'rules#index'
get 'festivals', to: 'festivals#index'
get 'posts', to: 'posts#index'
get 'posts/new', to: 'posts#new'
post 'posts', to: 'posts#create'
get 'spla1s', to: 'spla1s#index'
get 'spla2s', to: 'spla2s#index'
get 'spla3s', to: 'spla3s#index'
resources :splatoons
resources :list2s
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
    def index
    end
end

app/controllers/list2s_controller.rb
class List2sController < ApplicationController
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index  # indexアクションを定義した
     @posts = Post.all
    end
    def new
    end
    def create
        Post.create(content: params[:content])
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
    def index  # indexアクションを定義した
    end
end

app/controllers/spla1s_controller.rb
class Spla1sController < ApplicationController
     def index  # indexアクションを定義した
     end
end

app/controllers/spla2s_controller.rb
class Spla2sController < ApplicationController
    def index
    end
end

app/controllers/spla3s_controller.rb
class Spla3sController < ApplicationController
    def index
    end
end

app/controllers/splatoons_controller.rb
class SplatoonsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/list2s_helper.rb
module List2sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/helpers/spla1s_helper.rb
module Spla1sHelper
end

app/helpers/spla2s_helper.rb
module Spla2sHelper
end

app/helpers/spla3s_helper.rb
module Spla3sHelper
end

app/helpers/splatoons_helper.rb
module SplatoonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
<title>Splatoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 </head>
  <body>


   <header class="header">
    <h1 class="grid-6"> <%= link_to image_tag("logo.png", class:"logo"), "/" %> </h1>
   </header>
   <div class = "top-bar">
<ul  class="pull-down-list">
            <li class="list1"><%= link_to 'トップ', root_path, class: 'link', method: :GET %></li>
            <li class="list2"><%= link_to 'メンバー紹介', list2s_index_path, class: 'link', method: :GET %></li>
            <li class="list3"><%= link_to 'ルール説明', rules_path, class: 'link', method: :GET %></li>
            <li class="list4"><%= link_to 'フェスまとめ', festivals_path, class: 'link', method: :GET %></li>
            <li class="list5"><%= link_to '掲示板', posts_path, class: 'link', method: :GET %></li>
  </ul>
</div>
       <%= yield %>
    <footer>
      <p>
        Copyright KY-Splatoon-Club 2022.
      </p>
    </footer>
  </body>
</html>